env:
  global:
    - LD_LIBRARY_PATH=/usr/local/lib
install:
  - curl https://static.rust-lang.org/rustup.sh | sudo sh -
  - sudo apt-get install zlib1g-dev
script:
  - rustc --version
  - cargo build